/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as _authenticatedRouteImport } from './routes/__authenticated'
import { Route as _authenticatedIndexRouteImport } from './routes/__authenticated/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedRoute = _authenticatedRouteImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedIndexRoute = _authenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => _authenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof _authenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof _authenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__authenticated': typeof _authenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/__authenticated/': typeof _authenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/register' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/'
  id:
    | '__root__'
    | '/__authenticated'
    | '/login'
    | '/register'
    | '/__authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authenticatedRoute: typeof _authenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated': {
      id: '/__authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated/': {
      id: '/__authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _authenticatedIndexRouteImport
      parentRoute: typeof _authenticatedRoute
    }
  }
}

interface _authenticatedRouteChildren {
  _authenticatedIndexRoute: typeof _authenticatedIndexRoute
}

const _authenticatedRouteChildren: _authenticatedRouteChildren = {
  _authenticatedIndexRoute: _authenticatedIndexRoute,
}

const _authenticatedRouteWithChildren = _authenticatedRoute._addFileChildren(
  _authenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authenticatedRoute: _authenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
