/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as _authenticatedRouteImport } from './routes/__authenticated'
import { Route as _authenticatedLayoutRouteImport } from './routes/__authenticated/_layout'
import { Route as _authenticatedLayoutIndexRouteImport } from './routes/__authenticated/_layout.index'
import { Route as _authenticatedLayoutTaskRouteImport } from './routes/__authenticated/_layout.task'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedRoute = _authenticatedRouteImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedLayoutRoute = _authenticatedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedLayoutIndexRoute =
  _authenticatedLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => _authenticatedLayoutRoute,
  } as any)
const _authenticatedLayoutTaskRoute =
  _authenticatedLayoutTaskRouteImport.update({
    id: '/task',
    path: '/task',
    getParentRoute: () => _authenticatedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/task': typeof _authenticatedLayoutTaskRoute
  '/': typeof _authenticatedLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/task': typeof _authenticatedLayoutTaskRoute
  '/': typeof _authenticatedLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__authenticated': typeof _authenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/__authenticated/_layout': typeof _authenticatedLayoutRouteWithChildren
  '/__authenticated/_layout/task': typeof _authenticatedLayoutTaskRoute
  '/__authenticated/_layout/': typeof _authenticatedLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/register' | '/task' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/register' | '/task' | '/'
  id:
    | '__root__'
    | '/__authenticated'
    | '/login'
    | '/register'
    | '/__authenticated/_layout'
    | '/__authenticated/_layout/task'
    | '/__authenticated/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authenticatedRoute: typeof _authenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated': {
      id: '/__authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated/_layout': {
      id: '/__authenticated/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _authenticatedLayoutRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/_layout/': {
      id: '/__authenticated/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _authenticatedLayoutIndexRouteImport
      parentRoute: typeof _authenticatedLayoutRoute
    }
    '/__authenticated/_layout/task': {
      id: '/__authenticated/_layout/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof _authenticatedLayoutTaskRouteImport
      parentRoute: typeof _authenticatedLayoutRoute
    }
  }
}

interface _authenticatedLayoutRouteChildren {
  _authenticatedLayoutTaskRoute: typeof _authenticatedLayoutTaskRoute
  _authenticatedLayoutIndexRoute: typeof _authenticatedLayoutIndexRoute
}

const _authenticatedLayoutRouteChildren: _authenticatedLayoutRouteChildren = {
  _authenticatedLayoutTaskRoute: _authenticatedLayoutTaskRoute,
  _authenticatedLayoutIndexRoute: _authenticatedLayoutIndexRoute,
}

const _authenticatedLayoutRouteWithChildren =
  _authenticatedLayoutRoute._addFileChildren(_authenticatedLayoutRouteChildren)

interface _authenticatedRouteChildren {
  _authenticatedLayoutRoute: typeof _authenticatedLayoutRouteWithChildren
}

const _authenticatedRouteChildren: _authenticatedRouteChildren = {
  _authenticatedLayoutRoute: _authenticatedLayoutRouteWithChildren,
}

const _authenticatedRouteWithChildren = _authenticatedRoute._addFileChildren(
  _authenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  _authenticatedRoute: _authenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
